2024-05-31 17:10:24,994 - __main__ - ERROR - The file nonexistent_file.txt was not found.
Traceback (most recent call last):
  File "C:\Users\ddevraj\PycharmProjects\pythonProject\practice 2\error_find_program.py", line 13, in read_file
    with open(file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'nonexistent_file.txt'
